# Generated by Django 2.1.7 on 2019-04-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190322_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.IntegerField(choices=[(1, 'In library'), (2, 'Borrowed'), (3, 'Overdue')], default=1),
        ),
    ]
