# Generated by Django 2.1.1 on 2019-03-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190322_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='searchableReleaseDate',
            field=models.CharField(default=1880, max_length=10),
            preserve_default=False,
        ),
    ]
