# Generated by Django 2.1.7 on 2019-03-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_movie_searchablereleasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='format',
            field=models.CharField(choices=[(None, ''), ('V', 'VHS Tape'), ('D', 'DVD'), ('B', 'Blu-ray'), ('K', '4K UHD')], default='D', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
