# Generated by Django 2.1.7 on 2019-03-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190326_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrequest',
            name='end_date',
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='borrow_duration',
            field=models.IntegerField(choices=[(1, '1 day'), (2, '2 days'), (3, '3 days'), (4, '4 days'), (5, '5 days'), (6, '6 days'), (7, '1 week'), (8, '8 days'), (9, '9 days'), (10, '10 days'), (11, '11 days'), (12, '12 days'), (13, '13 days'), (14, '2 weeks')], default=3),
        ),
    ]
