# Generated by Django 2.1.7 on 2019-04-12 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190329_2054'),
        ('main', '0003_auto_20190331_2344'),
    ]

    operations = [
    ]
