# Generated by Django 2.1.7 on 2019-04-24 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190413_2306'),
        ('main', '0006_merge_20190410_2303'),
    ]

    operations = [
    ]
