# Generated by Django 2.1.7 on 2019-04-25 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_merge_20190424_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_personal_info', models.BooleanField(default=True)),
                ('start_loan_exchange_type', models.CharField(choices=[('PICK_UP', 'Pick up'), ('DROP_OFF', 'Drop off')], default='PICK_UP', max_length=12)),
                ('end_loan_exchange_type', models.CharField(choices=[('PICK_UP', 'Pick up'), ('DROP_OFF', 'Drop off')], default='DROP_OFF', max_length=12)),
                ('exchange_location_choice', models.CharField(choices=[('DEFAULT', 'My address'), ('OTHER', 'Other')], default='DEFAULT', max_length=12)),
                ('exchange_location', models.CharField(blank=True, max_length=100)),
                ('favorite_genre', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
